#!/usr/bin/env bash
# Regenerate THIRD_PARTY_NOTICES.md from the modules linked into the binary.
#
# `a` statically links BSD-3-Clause and Apache-2.0 dependencies, and both attach
# conditions to *binary* redistribution: BSD-3 clause 2 requires the copyright
# notice and disclaimer to accompany the distribution, and Apache-2.0 4(a)/4(d)
# require the license and any NOTICE attributions. Shipping only the project's
# own MIT LICENSE.md satisfies neither.
#
# `go list -deps` walks the main package's imports, so test-only modules such as
# testify are correctly excluded -- they are not in the shipped binary.
#
# Lives as a script rather than an inline Justfile recipe because the go list
# format string is full of {{...}}, which just would try to interpolate.
set -euo pipefail

cd "$(dirname "$0")/.."

out=THIRD_PARTY_NOTICES.md
module=$(go list -m)

{
  echo "# Third-Party Notices"
  echo
  echo "\`a\` statically links the Go modules below. Their license terms require"
  echo "that these notices accompany binary distributions."
  echo
  echo "Generated by \`just notices\` — do not edit by hand."
} >"$out"

go list -deps -f '{{with .Module}}{{.Path}}	{{.Version}}	{{.Dir}}{{end}}' . |
  sort -u |
  while IFS=$'\t' read -r path version dir; do
    [ -n "${dir:-}" ] || continue
    [ "$path" != "$module" ] || continue
    for f in LICENSE LICENSE.txt LICENSE.md COPYING NOTICE; do
      [ -f "$dir/$f" ] || continue
      # The filename goes in the heading, not a subheading: a module shipping
      # both LICENSE and NOTICE (gopkg.in/yaml.v3 does) would otherwise emit the
      # same heading twice and trip markdownlint MD024. ```text, not a bare
      # fence, for MD040 -- this file is linted like any other markdown here.
      printf '\n## %s %s — %s\n\n```text\n' "$path" "$version" "$f" >>"$out"
      cat "$dir/$f" >>"$out"
      printf '```\n' >>"$out"
    done
  done

printf 'wrote %s (%s modules)\n' "$out" "$(grep -c '^## ' "$out")"
